const OK = 200;
const CREATED = 201;
const BAD_REQUEST_ERR = 400;
const NOT_FOUND_ERR = 404;
const INTERNAL_SERVER_ERR = 500;

module.exports = {
  OK,
  CREATED,
  BAD_REQUEST_ERR,
  NOT_FOUND_ERR,
  INTERNAL_SERVER_ERR,
};
